### ISSUE TITLE
Training Data

### ISSUE THREAD

**Issue by ThomasCai35** [bdaiinstitute/theia#12]
Thanks for your excellent work! You mentioned that Theia model had much much smaller training dataset, smaller model size, and smaller resolution compared to those teacher models. Plus, you mentioned that you thought training data could outweigh supervision on vision task. So I launched an issue. Would Theia model work better with the development of the training dataset? If so,  did you have any recommendation or ideas about training dataset which would develop the performance possibly. Thanks.

**Comment by jshang-bdai** [comment]
I guess datasets larger than ImageNet-1K could work!

**Comment by Mixanik-43** [comment]
@jshang-bdai Thanks for the great work! I see the code for Open X-Embodiment dataset in this repository, and distilling foundation vision models on Open X-Embodiment seems reasonable for robotic down-stream tasks. However, these results are not reported in the paper. Could you share any results of training Theia on other datasets than ImageNet, if you tried it?

**Comment by elicassion** [comment]
@Mixanik-43 

We got lower training & evaluation losses on OXE, but we are skeptical that the lower losses were due to the poor visual diversity of the OXE dataset. We don't have the full results on robot learning benchmarks of that checkpoint, but some very early results showed that it was worse than being trained on ImageNet.

**Comment by Mixanik-43** [comment]
@elicassion 
Thank you for your thoughtful response.
